### PR TITLE
Overwrite default language from tgtg lib

### PR DESCRIPTION
**Pull request by Dielee**

### CODE REVIEW

**Comment by MaxWinterstein** [comment]
What does this do? Is the login request email language based on this setting?

**Comment by Dielee** [comment]
Tgtg lib uses en-UK as language default. But that's not how the app does it.
If you are in germany for example, the app sends de-DE as accept-language header.

**Comment by MaxWinterstein** [comment]
Well, I am not really sure if this makes any difference, but it certainly won't hurt.

**Comment by MaxWinterstein** [comment]
Merged and released with `v1.10.0`, thanks!

**Pull request merged**
