### PR TITLE
Fix 403 error - Randomize UA generation with latest app version

### PR DESCRIPTION
**Pull request by Dielee**
Check and autoupdate TGTG useragent to latest app version from google play, as TGTG seems to block specific useragents.

### CODE REVIEW

**Comment by MaxWinterstein** [comment]
Yeah, this one looks good!

Will merge, release and update add-on later that day - when I find some time.

(And sorry again for the hassle, Gitlab is not my daily business, so I might did stupid)

**Comment by Dielee** [comment]
Hey Max, as I know you own a little developer at home and time is precious, you maybe want to add me as owner to this project ? This can speed things up. Think about it 😊

**Comment by MaxWinterstein** [comment]
> Hey Max, as I know you own a little developer at home and time is precious, you maybe want to add me as owner to this project ? This can speed things up. Think about it 😊

Sure thing! There is a lot of stuff that could be improved here. I will have a look at the permission system at github (Gitlab guy here)!

**Comment by Dielee** [comment]
Really nice, thanks for merging!

**Comment by MaxWinterstein** [comment]
Will have a look at #52 and do all the release stuff.

One day this could be completely automated...
________________________________

**Comment by Dielee** [comment]
Yeah, thanks. Is there a way to chat private ?
I have a few questions about releasing stuff in your repo.

**Comment by MaxWinterstein** [comment]
Sure thing, hit me up at github@winterstein.mx and suggest something. Telegram, WhatsApp, whatever pleases you.

**Pull request merged**
