### PR TITLE
A collection of improvements

### PR DESCRIPTION
**Pull request by Dielee**
- Fix error if data_dir not exists on filesystem
- Add cron schedule interval setting
- Add runtime randomizing
- Add fallback for old every_n_minutes setting
- Add option to define local language

### CODE REVIEW

**Comment by niklas1375** [comment]
@MaxWinterstein the cron scheduling feature would be really neat. Any chance you could look into this PR? :)

**Comment by MaxWinterstein** [comment]
Wow, totally forgot about that - got lost in my crowded inbox 😫

will take care of this soon ✌️

**Comment by MaxWinterstein** [comment]
Found some time 🥳 

This works great, thanks @Dielee and I apologize again for the delay. There is some new, small developer in my house, that takes all my attention. Currently he only chews my mouse, but we will get there! :)

**Comment by niklas1375** [comment]
Thanks to @Dielee for the contribution and @MaxWinterstein for merging - all the best to the little developer 😄

**Comment by MaxWinterstein** [comment]
> @MaxWinterstein for merging - all the best to the little developer 😄

hehe, thx, will do my best. And thx for the coffee ☕️ ❤️

**Pull request merged**
