### PR TITLE
[Feature] Add automatic intense fetch based on tgtg item data

### PR DESCRIPTION
**Pull request by Dielee**

### CODE REVIEW

**Comment by MaxWinterstein** [comment]
Hi @Dielee, sorry for the delay. There is hardly time for my projects 😞 

Some thoughts I have:
- Can we have some settings to enable/disable this?
- I would just add the `item` itself to `favourite_ids` instead, this would prevent another hit on the API that does not really get any new information.
- I know some shops that change the pickup/purchase time on weekends, this would be good to take care of.

Anyways, I like the idea and would love to merge this, once above-mentioned things were taken care of.

**Comment by Dielee** [comment]
Hi @MaxWinterstein, no problem, family first 👍 

- Can we have some settings to enable/disable this?
    - I added settings to turn this feature off. 
 
- I would just add the item itself to favourite_ids instead, this would prevent another hit on the API that does not really get any new information.
   - Yes, I thougt the same, but `get_items` doesn't deliver the neccesarry `next_sales_window_purchase_start` key.
      Therefore there is no other way then pull the item with the item_id from api to get the 
      `next_sales_window_purchase_start`  key. Take a look at the responses from tgtg here: [Link](https://github.com/ahivert/tgtg-python)

- I know some shops that change the pickup/purchase time on weekends, this would be good to take care of.  
  - We take care of this already . New purchase slots will be updated at 8,11,14,17 and 20 o'clock.

**Comment by MaxWinterstein** [comment]
Awesome, then let's rebase this thing and we are ready to merge!

**Comment by Dielee** [comment]
Maybe we should squash and merge ?

**Comment by MaxWinterstein** [comment]
> Maybe we should squash and merge ?

You need to rebase your branch on 'my' main branch, as there is a conflict somewhere. I can't merge it before.

image

**Comment by Dielee** [comment]
This should be able to merge now!

**Comment by Dielee** [comment]
So, rebase and merge is now possible

**Comment by MaxWinterstein** [comment]
Thanks!

**Pull request merged**
