### PR TITLE
Fix error 403 for blocked or old user agent

### PR DESCRIPTION
**Pull request by Dielee**

### CODE REVIEW

**Comment by MaxWinterstein** [comment]
This is so cool! I love the google-play-scraper part 😄 

Can you give it a quick rebase and a little squash? Would love to merge this - and keep your credits for the great work!

**Comment by Dielee** [comment]
So, rebased and squashed in [51267de](https://github.com/MaxWinterstein/toogoodtogo-ha-mqtt-bridge/pull/49/commits/51267dee2b402842d30ad4101e1b9cba8b19bef6). Ready to merge!

**Comment by MaxWinterstein** [comment]
@Dielee Still not mergeable :( 

Not sure what happened here, but there are still 17 commits to be applied. Might have a second look?

**Comment by Dielee** [comment]
I will close this PR and fetch upstream source. Wait a minute.

**Pull request closed without merging**
