### PR TITLE
update tgtg; Add local token store procedure

### PR DESCRIPTION
**Pull request by Dielee**
Add local token store procedure to prevent repeated login emailing from tgtg.

### CODE REVIEW

**Comment by MaxWinterstein** [comment]
Awesome, thanks ❤️ 

One thing that crosses my mind when working on that from the other side (see https://github.com/MaxWinterstein/tgtg-python), what happens when I turn off the bridge for longer than the `access_token_lifetime`? I guess this case is not handled within `tgtg` and might end up in an exception loop?

**Comment by Dielee** [comment]
I am currently trying out what happens after expiration.
Possibly a new authorization can be done with the refresh_token.

Please wait with commiting until this case is safe!

**Comment by MaxWinterstein** [comment]
> I am currently trying out what happens after expiration. Possibly a new authorization can be done with the refresh_token.
> 
> Please wait with commiting until this case is safe!

Great, let me know when it's done 😀

**Comment by Dielee** [comment]
So, refreshing token while running tgtg bot is working. 
If the application is not running, the first loggin will always be done by credentials.

**Comment by MaxWinterstein** [comment]
nice 👍  

will have a look and test in detail later.

**Comment by MaxWinterstein** [comment]
Works like a charm, thanks for the pull request!

**Pull request merged**
